### ISSUE TITLE
URL is invalid

### ISSUE THREAD

**Issue by zghwi** [IreTheKID/ReplStats#1]
# hi
Every time I enter a URL, it says it is invalid. Like that: https://repl.it/@ZDev1/web

It is my first repl, and it says it is invalid.

**Comment by frissyn** [comment]
@zplusfour ReplStats takes URLs for web-hosted REPLs, not the code itself. For example, if you made a Flask or Express app at @zplusfour/my-web-app then putting in my-web-app.zplusfour.repl.co would work.

Here's an example:

![image](https://storage.googleapis.com/replit/images/1611238922144_9c3e7c1d2f8829e43ffe0264123f25fb.png)
